name: CI

on:
  workflow_dispatch:
    inputs:
      gdal_version:
        description: "GDAL version to build"
        required: true
        default: "3.8.3"
      python_version:
        description: "Python version to target"
        required: true
        default: "3.11"

env:
  GDAL_VERSION: ${{ github.event.inputs.gdal_version }}
  GDAL_VERSION_TAG: ${{ github.event.inputs.gdal_version }}
  PYTHON_VERSION: ${{ github.event.inputs.python_version }}

jobs:
  build-layer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with GDAL
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: dockerfiles/Dockerfile
          load: true
          build-args: |
            GDAL_VERSION=${{ env.GDAL_VERSION }}
          tags: lambda-gdal:${{ env.GDAL_VERSION }}

      - name: Run container to create GDAL Lambda Layer
        run: |
          docker run \
            --platform=linux/amd64 \
            --rm \
            -v ${{ github.workspace }}:/local \
            lambda-gdal:${{ env.GDAL_VERSION }} \
            /local/scripts/create-layer.sh
          echo "Layer zip created"

      - name: Upload GDAL Layer artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdal-layer-${{ env.GDAL_VERSION }}-python${{ env.PYTHON_VERSION }}
          path: layer.zip
          if-no-files-found: error

      - name: Add download link to summary
        run: |
          echo "### ✅ GDAL Layer Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "- GDAL version: **${{ env.GDAL_VERSION }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Python version: **${{ env.PYTHON_VERSION }}**" >> $GITHUB_STEP_SUMMARY
          echo "- [⬇️ Download Layer Zip](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
